version: "3"

services:
    api:
        build: 
            context: .
            dockerfile: Dockerfile.api
        restart: always
        ports: 
            - "${WEB_PORT}:80"
        networks:
            - mt-skeleton-network
        environment:
            - SQLALCHEMY_DATABASE_URL=postgres://postgres@db/${DATABASE_NAME}
            # :${POSTGRES_PASSWORD}
             
    db:
        build: 
            context: .
            dockerfile: Dockerfile.postgres
        environment: 
            # POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: "${DATABASE_NAME}"
            POSTGRES_HOST_AUTH_METHOD: trust
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - mt-skeleton-network
        ports:
            - ${POSTGRES_PORT}:5432
    
    pgadmin:
        build: 
            context: .
            dockerfile: Dockerfile.pgadmin
        ports: 
            - "${PGADMIN_PORT}:80"
        volumes:
            - pgadmin_data:/var/lib/pgadmin
        restart: always
        depends_on:
            - db
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        networks:
            - mt-skeleton-network

volumes:
    postgres_data:
    upload_data:
    pgadmin_data:
        driver: local

networks:
    mt-skeleton-network:
        driver: bridge