FROM tiangolo/uvicorn-gunicorn:python3.8

WORKDIR /
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY . /
RUN rm /usr/bin/X11/X11
RUN  /usr/local/bin/python -m pip install --upgrade pip
RUN  pip3 install -r /requirements.txt

CMD [ "uvicorn", "main:api","--reload", "--workers","3","--host", "0.0.0.0", "--port", "80"]